//! Task Management with Projections
//!
//! This example demonstrates:
//! - Creating events from a task management domain using modern event patterns
//! - Building multiple projections (read models) from the same events
//! - Using checkpoints to track projection progress
//! - Running projections concurrently
//! - ApplyEvent trait for type-safe event handling
//!
//! Run with: `cargo run --example task-projections --features "memory,projections,macros"`

use async_trait::async_trait;
use chrono::{DateTime, Utc};
use event_sauce::event_sauce_memory::InMemoryEventBus;
use event_sauce::event_sauce_projections;
use event_sauce::{ApplyEvent, DomainEvent, EventBus, EventEnvelope, EventFilter, Result};
use event_sauce_macros::{AggregateError, AggregateId, AggregateState, Event};
use futures::StreamExt;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

// Re-export projection types for convenience
use event_sauce_projections::{
    Checkpoint, CheckpointStore, InMemoryCheckpointStore, Projection, ProjectionRunner,
};

/// Task status enum
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash, Default)]
enum TaskStatus {
    #[default]
    Todo,
    InProgress,
    Completed,
}

// Individual event structs with their own data
#[derive(Debug, Clone, Serialize, Deserialize)]
struct Created {
    task_id: Uuid,
    title: String,
    assignee: String,
    timestamp: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct StatusChanged {
    task_id: Uuid,
    old_status: TaskStatus,
    new_status: TaskStatus,
    timestamp: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct Assigned {
    task_id: Uuid,
    from_assignee: String,
    to_assignee: String,
    timestamp: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct Completed {
    task_id: Uuid,
    timestamp: DateTime<Utc>,
}

/// Task aggregate ID wrapper
///
/// Using the AggregateId derive macro to auto-implement:
/// - AggregateId trait (to_uuid method)
/// - Display trait (delegates to inner Uuid)
#[derive(AggregateId, Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
struct TaskId(Uuid);

/// Error type for task operations
///
/// Using the AggregateError derive macro to auto-implement the marker trait
#[derive(AggregateError, Debug, Clone, thiserror::Error)]
enum TaskError {
    #[error("Task not found")]
    NotFound,
    #[error("Invalid status transition from {from:?} to {to:?}")]
    InvalidStatusTransition {
        from: TaskStatus,
        to: TaskStatus,
    },
}

/// Task state containing business logic fields
///
/// The AggregateState macro will automatically generate TaskAggregate
/// with infrastructure fields (version, pending_events) and Aggregate trait impl.
#[derive(AggregateState, Debug, Clone, Default, Serialize, Deserialize)]
#[aggregate(id = "TaskId", event = "TaskEvent", error = "TaskError")]
struct TaskState {
    #[aggregate_id]
    id: TaskId,
    title: String,
    assignee: String,
    status: TaskStatus,
}

// Note: TaskAggregate is auto-generated by the AggregateState macro
// It includes: version, pending_events, and full Aggregate trait implementation

/// Task event enum using Event derive macro with ApplyEvent pattern
///
/// The Event macro automatically generates:
/// - DomainEvent implementation (event_type, event_version, occurred_at)
/// - Aggregate association (type Aggregate = TaskAggregate)
/// - apply_event method that calls validate, apply, post_validate
/// - to_envelope() and from_envelope() methods
#[derive(Event, Debug, Clone, Serialize, Deserialize)]
#[event(version = 1, type_prefix = "Task", aggregate = "TaskAggregate")]
enum TaskEvent {
    Created(Created),
    StatusChanged(StatusChanged),
    Assigned(Assigned),
    Completed(Completed),
}

// ============================================================================
// ApplyEvent implementations for each event type
// ============================================================================
//
// Note: We implement ApplyEvent for TaskAggregate (the generated wrapper).
// Thanks to Deref/DerefMut, we can access TaskState fields directly!

/// When a task is created, initialize its state
impl ApplyEvent<TaskAggregate, TaskError> for Created {
    fn apply(&self, task: &mut TaskAggregate) {
        // Access state fields directly via DerefMut
        task.title = self.title.clone();
        task.assignee = self.assignee.clone();
        task.status = TaskStatus::Todo;
    }
}

/// When status changes, update the task status with validation
impl ApplyEvent<TaskAggregate, TaskError> for StatusChanged {
    fn validate(&self, task: &TaskAggregate) -> std::result::Result<(), TaskError> {
        // Validate status transitions (no changes allowed from Completed)
        match (&task.status, &self.new_status) {
            (TaskStatus::Completed, _) => Err(TaskError::InvalidStatusTransition {
                from: task.status.clone(),
                to: self.new_status.clone(),
            }),
            _ => Ok(()),
        }
    }

    fn apply(&self, task: &mut TaskAggregate) {
        task.status = self.new_status.clone();
    }
}

/// When a task is reassigned, update the assignee
impl ApplyEvent<TaskAggregate, TaskError> for Assigned {
    fn apply(&self, task: &mut TaskAggregate) {
        task.assignee = self.to_assignee.clone();
    }
}

/// When a task is completed, mark it as done
impl ApplyEvent<TaskAggregate, TaskError> for Completed {
    fn apply(&self, task: &mut TaskAggregate) {
        task.status = TaskStatus::Completed;
    }
}

/// Helper function to create event envelopes using the new to_envelope() API
fn create_event(event: TaskEvent, aggregate_id: Uuid) -> Result<EventEnvelope> {
    // Use the new to_envelope() method - much cleaner!
    // Aggregate type is automatically determined from TaskEvent::Aggregate
    event.to_envelope(aggregate_id)
}

/// Projection 1: Task Count by Status
///
/// Maintains a count of tasks in each status.
#[derive(Debug)]
struct TaskCountByStatusProjection {
    counts: HashMap<TaskStatus, u64>,
}

impl TaskCountByStatusProjection {
    fn new() -> Self {
        let mut counts = HashMap::new();
        counts.insert(TaskStatus::Todo, 0);
        counts.insert(TaskStatus::InProgress, 0);
        counts.insert(TaskStatus::Completed, 0);
        Self { counts }
    }

    fn get_count(&self, status: &TaskStatus) -> u64 {
        *self.counts.get(status).unwrap_or(&0)
    }

    fn total_tasks(&self) -> u64 {
        self.counts.values().sum()
    }
}

#[async_trait]
impl Projection for TaskCountByStatusProjection {
    fn name(&self) -> &str {
        "task_count_by_status"
    }

    async fn handle(&mut self, event: &EventEnvelope) -> Result<()> {
        // Use the new try_into_event() method for cleaner deserialization
        let event_data: TaskEvent = event.try_into_event()?;

        match event_data {
            TaskEvent::Created(_) => {
                *self.counts.entry(TaskStatus::Todo).or_insert(0) += 1;
            }
            TaskEvent::StatusChanged(StatusChanged {
                old_status,
                new_status,
                ..
            }) => {
                // Decrement old status count
                if let Some(count) = self.counts.get_mut(&old_status) {
                    *count = count.saturating_sub(1);
                }
                // Increment new status count
                *self.counts.entry(new_status).or_insert(0) += 1;
            }
            TaskEvent::Completed(_) => {
                // Completed event might be separate from status change
                // This is idempotent if status was already changed to Completed
            }
            TaskEvent::Assigned(_) => {
                // Assignment doesn't affect status counts
            }
        }

        Ok(())
    }
}

/// Projection 2: Tasks by Assignee
///
/// Maintains a list of task IDs for each assignee.
#[derive(Debug)]
struct TasksByAssigneeProjection {
    assignments: HashMap<String, Vec<Uuid>>,
}

impl TasksByAssigneeProjection {
    fn new() -> Self {
        Self {
            assignments: HashMap::new(),
        }
    }

    fn get_tasks_for_assignee(&self, assignee: &str) -> Vec<Uuid> {
        self.assignments.get(assignee).cloned().unwrap_or_default()
    }

    fn assignee_count(&self) -> usize {
        self.assignments.len()
    }
}

#[async_trait]
impl Projection for TasksByAssigneeProjection {
    fn name(&self) -> &str {
        "tasks_by_assignee"
    }

    async fn handle(&mut self, event: &EventEnvelope) -> Result<()> {
        // Use the new try_into_event() method for cleaner deserialization
        let event_data: TaskEvent = event.try_into_event()?;

        match event_data {
            TaskEvent::Created(Created {
                task_id, assignee, ..
            }) => {
                self.assignments
                    .entry(assignee)
                    .or_insert_with(Vec::new)
                    .push(task_id);
            }
            TaskEvent::Assigned(Assigned {
                task_id,
                from_assignee,
                to_assignee,
                ..
            }) => {
                // Remove from old assignee
                if let Some(tasks) = self.assignments.get_mut(&from_assignee) {
                    tasks.retain(|&id| id != task_id);
                }
                // Add to new assignee
                self.assignments
                    .entry(to_assignee)
                    .or_insert_with(Vec::new)
                    .push(task_id);
            }
            _ => {
                // Other events don't affect assignments
            }
        }

        Ok(())
    }
}

/// Projection 3: Completed Tasks Counter
///
/// Simple projection that counts completed tasks.
#[derive(Debug)]
struct CompletedTasksProjection {
    count: u64,
    last_completed_task_id: Option<Uuid>,
}

impl CompletedTasksProjection {
    fn new() -> Self {
        Self {
            count: 0,
            last_completed_task_id: None,
        }
    }

    fn get_count(&self) -> u64 {
        self.count
    }
}

#[async_trait]
impl Projection for CompletedTasksProjection {
    fn name(&self) -> &str {
        "completed_tasks_counter"
    }

    async fn handle(&mut self, event: &EventEnvelope) -> Result<()> {
        // Only process Task.Completed events
        if event.event_type == "Task.Completed" {
            // Use the new try_into_event() method
            let event_data: TaskEvent = event.try_into_event()?;

            if let TaskEvent::Completed(Completed { task_id, .. }) = event_data {
                self.count += 1;
                self.last_completed_task_id = Some(task_id);
            }
        }

        Ok(())
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    println!("=== Task Management with Projections ===\n");

    // Create event bus
    let bus = InMemoryEventBus::new();
    println!("✓ Created event bus");

    // Create checkpoint store
    let checkpoint_store = InMemoryCheckpointStore::new();
    println!("✓ Created checkpoint store\n");

    // Create projections
    println!("--- Building Projections ---");

    let status_projection = TaskCountByStatusProjection::new();
    let assignee_projection = TasksByAssigneeProjection::new();
    let completed_projection = CompletedTasksProjection::new();

    println!("✓ Created 3 projections");

    // Create runners
    let mut status_runner = ProjectionRunner::new(status_projection);
    let mut assignee_runner = ProjectionRunner::new(assignee_projection);
    let mut completed_runner = ProjectionRunner::new(completed_projection);

    // Subscribe to events (all projections get all events)
    let status_stream = bus.subscribe(EventFilter::all()).await?;
    let assignee_stream = bus.subscribe(EventFilter::all()).await?;
    let completed_stream = bus
        .subscribe(EventFilter::by_event_type("Task.Completed"))
        .await?;

    println!("✓ Subscribed projections to event streams\n");

    // Publish a series of task events
    println!("--- Publishing Task Events ---");

    let task1_id = Uuid::new_v4();
    let task2_id = Uuid::new_v4();
    let task3_id = Uuid::new_v4();

    // Task 1: Created by Alice
    let event = create_event(
        TaskEvent::Created(Created {
            task_id: task1_id,
            title: "Implement authentication".to_string(),
            assignee: "alice".to_string(),
            timestamp: Utc::now(),
        }),
        task1_id,
    )?;
    bus.publish(event).await?;
    println!("✓ Task 1 created (Alice): 'Implement authentication'");

    // Task 2: Created by Bob
    let event = create_event(
        TaskEvent::Created(Created {
            task_id: task2_id,
            title: "Write documentation".to_string(),
            assignee: "bob".to_string(),
            timestamp: Utc::now(),
        }),
        task2_id,
    )?;
    bus.publish(event).await?;
    println!("✓ Task 2 created (Bob): 'Write documentation'");

    // Task 3: Created by Alice
    let event = create_event(
        TaskEvent::Created(Created {
            task_id: task3_id,
            title: "Fix bug #123".to_string(),
            assignee: "alice".to_string(),
            timestamp: Utc::now(),
        }),
        task3_id,
    )?;
    bus.publish(event).await?;
    println!("✓ Task 3 created (Alice): 'Fix bug #123'");

    // Task 1: Status changed to InProgress
    let event = create_event(
        TaskEvent::StatusChanged(StatusChanged {
            task_id: task1_id,
            old_status: TaskStatus::Todo,
            new_status: TaskStatus::InProgress,
            timestamp: Utc::now(),
        }),
        task1_id,
    )?;
    bus.publish(event).await?;
    println!("✓ Task 1 moved to In Progress");

    // Task 2: Assigned from Bob to Charlie
    let event = create_event(
        TaskEvent::Assigned(Assigned {
            task_id: task2_id,
            from_assignee: "bob".to_string(),
            to_assignee: "charlie".to_string(),
            timestamp: Utc::now(),
        }),
        task2_id,
    )?;
    bus.publish(event).await?;
    println!("✓ Task 2 reassigned from Bob to Charlie");

    // Task 1: Completed
    let event = create_event(
        TaskEvent::StatusChanged(StatusChanged {
            task_id: task1_id,
            old_status: TaskStatus::InProgress,
            new_status: TaskStatus::Completed,
            timestamp: Utc::now(),
        }),
        task1_id,
    )?;
    bus.publish(event).await?;
    println!("✓ Task 1 moved to Completed");

    let event = create_event(
        TaskEvent::Completed(Completed {
            task_id: task1_id,
            timestamp: Utc::now(),
        }),
        task1_id,
    )?;
    bus.publish(event).await?;
    println!("✓ Task 1 completed");

    // Task 3: Status changed to InProgress
    let event = create_event(
        TaskEvent::StatusChanged(StatusChanged {
            task_id: task3_id,
            old_status: TaskStatus::Todo,
            new_status: TaskStatus::InProgress,
            timestamp: Utc::now(),
        }),
        task3_id,
    )?;
    bus.publish(event).await?;
    println!("✓ Task 3 moved to In Progress\n");

    println!("--- Processing Events (with Checkpointing) ---");

    // Process events with checkpoint tracking
    let mut event_count = 0;
    status_runner
        .run_with_callback(status_stream.take(8), {
            let checkpoint_store = checkpoint_store.clone();
            move |event| {
                let checkpoint_store = checkpoint_store.clone();
                let event_id = event.id;
                event_count += 1;
                let seq = event_count;
                async move {
                    let checkpoint = Checkpoint::new("task_count_by_status", event_id, seq);
                    checkpoint_store
                        .save("task_count_by_status", checkpoint)
                        .await?;
                    Ok(())
                }
            }
        })
        .await?;
    println!("✓ Status projection processed (with checkpoints)");

    assignee_runner
        .run_with_callback(assignee_stream.take(8), {
            let checkpoint_store = checkpoint_store.clone();
            move |event| {
                let checkpoint_store = checkpoint_store.clone();
                let event_id = event.id;
                let seq = i64::from(event.event_version.as_i32());
                async move {
                    let checkpoint = Checkpoint::new("tasks_by_assignee", event_id, seq);
                    checkpoint_store
                        .save("tasks_by_assignee", checkpoint)
                        .await?;
                    Ok(())
                }
            }
        })
        .await?;
    println!("✓ Assignee projection processed (with checkpoints)");

    // Only 1 Task.Completed event was published
    completed_runner.run(completed_stream.take(1)).await?;
    println!("✓ Completed tasks projection processed\n");

    // Display results
    println!("=== Projection Results ===\n");

    // Status counts
    println!("📊 Task Count by Status:");
    println!(
        "  - Todo: {}",
        status_runner.projection().get_count(&TaskStatus::Todo)
    );
    println!(
        "  - In Progress: {}",
        status_runner
            .projection()
            .get_count(&TaskStatus::InProgress)
    );
    println!(
        "  - Completed: {}",
        status_runner.projection().get_count(&TaskStatus::Completed)
    );
    println!("  - Total: {}\n", status_runner.projection().total_tasks());

    // Tasks by assignee
    println!("👥 Tasks by Assignee:");
    let alice_tasks = assignee_runner.projection().get_tasks_for_assignee("alice");
    let bob_tasks = assignee_runner.projection().get_tasks_for_assignee("bob");
    let charlie_tasks = assignee_runner
        .projection()
        .get_tasks_for_assignee("charlie");

    println!("  - Alice: {} task(s)", alice_tasks.len());
    println!("  - Bob: {} task(s)", bob_tasks.len());
    println!("  - Charlie: {} task(s)", charlie_tasks.len());
    println!(
        "  - Total assignees: {}\n",
        assignee_runner.projection().assignee_count()
    );

    // Completed tasks
    println!(
        "✅ Completed Tasks: {}\n",
        completed_runner.projection().get_count()
    );

    // Show checkpoint status
    println!("=== Checkpoint Status ===\n");

    if let Some(checkpoint) = checkpoint_store.load("task_count_by_status").await? {
        println!("✓ Status projection checkpoint:");
        println!("  - Sequence: {}", checkpoint.sequence());
        println!("  - Timestamp: {}", checkpoint.timestamp());
    }

    if let Some(checkpoint) = checkpoint_store.load("tasks_by_assignee").await? {
        println!("✓ Assignee projection checkpoint:");
        println!("  - Sequence: {}", checkpoint.sequence());
        println!("  - Timestamp: {}", checkpoint.timestamp());
    }

    println!("\n=== Example Complete ===");
    println!("\nKey Takeaways:");
    println!("1. Multiple projections can process the same events");
    println!("2. Each projection builds its own optimized read model");
    println!("3. Checkpoints enable resuming projections after restart");
    println!("4. Event filtering reduces processing for specialized projections");

    Ok(())
}
