//! Projection trait for building read models from event streams.
//!
//! Projections transform events into query-optimized views. The [`Projection`] trait
//! provides a standard interface that integrates with the subscription system for
//! automatic event routing and filter configuration.
//!
//! # Using with the `projection!` macro
//!
//! The [`projection!`](crate::projection!) macro automatically implements this trait:
//!
//! ```ignore
//! projection! {
//!     pub struct UserCountProjection {
//!         state: u64,
//!
//!         on UserEvent::Created |proj, _event| {
//!             *proj.state_mut() += 1;
//!         },
//!     }
//! }
//!
//! // Projection trait is implemented automatically:
//! assert_eq!(UserCountProjection::NAME, "UserCountProjection");
//! ```
//!
//! # Manual implementation
//!
//! ```ignore
//! use event_sauce_core::{Projection, EventEnvelope};
//!
//! struct MyProjection { count: u64 }
//!
//! #[async_trait::async_trait]
//! impl Projection for MyProjection {
//!     type State = u64;
//!     const NAME: &'static str = "MyProjection";
//!
//!     fn handled_event_types() -> Option<Vec<&'static str>> {
//!         Some(vec!["User.Created", "User.Updated"])
//!     }
//!
//!     async fn handle(&mut self, envelope: &EventEnvelope) -> event_sauce_core::Result<()> {
//!         self.count += 1;
//!         Ok(())
//!     }
//!
//!     fn state(&self) -> &u64 { &self.count }
//!     fn state_mut(&mut self) -> &mut u64 { &mut self.count }
//! }
//! ```

use async_trait::async_trait;

use crate::{EventEnvelope, EventFilter};

/// Trait for event projections (read models).
///
/// Projections consume events and build query-optimized views. This trait
/// provides a standard interface that enables automatic integration with
/// the subscription system.
///
/// # Automatic subscription wiring
///
/// When used with [`EventStore::projection_subscription`](crate::EventStore::projection_subscription),
/// the projection's [`NAME`](Self::NAME) is used as the subscription name and
/// [`event_filter`](Self::event_filter) configures the subscription filter automatically.
#[async_trait]
pub trait Projection: Send {
    /// The projection state type.
    type State;

    /// The projection name, used as the default subscription name.
    ///
    /// Auto-generated by the `projection!` macro from the struct name
    /// (e.g., `"OrderSummaryProjection"`).
    const NAME: &'static str;

    /// Returns the event types this projection handles.
    ///
    /// `None` means "all events." `Some(vec)` returns the `EVENT_TYPE`
    /// strings for each handled event.
    fn handled_event_types() -> Option<Vec<&'static str>>;

    /// Returns an [`EventFilter`] matching only handled events.
    ///
    /// The default implementation converts [`handled_event_types`](Self::handled_event_types)
    /// into an appropriate filter: `None` becomes [`EventFilter::All`],
    /// and `Some(types)` becomes [`EventFilter::any_of_event_types`].
    #[must_use]
    fn event_filter() -> EventFilter {
        match Self::handled_event_types() {
            None => EventFilter::All,
            Some(types) => EventFilter::any_of_event_types(types),
        }
    }

    /// Handle an event envelope, updating projection state.
    ///
    /// # Errors
    ///
    /// Returns an error if event deserialization or handler logic fails.
    async fn handle(&mut self, envelope: &EventEnvelope) -> crate::Result<()>;

    /// Returns an immutable reference to the projection state.
    fn state(&self) -> &Self::State;

    /// Returns a mutable reference to the projection state.
    fn state_mut(&mut self) -> &mut Self::State;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_fixtures::create_test_envelope;

    struct CountingProjection {
        count: u64,
    }

    #[async_trait]
    impl Projection for CountingProjection {
        type State = u64;
        const NAME: &'static str = "CountingProjection";

        fn handled_event_types() -> Option<Vec<&'static str>> {
            Some(vec!["UserCreated", "UserUpdated"])
        }

        async fn handle(&mut self, _envelope: &EventEnvelope) -> crate::Result<()> {
            self.count += 1;
            Ok(())
        }

        fn state(&self) -> &u64 {
            &self.count
        }

        fn state_mut(&mut self) -> &mut u64 {
            &mut self.count
        }
    }

    #[test]
    fn test_projection_name() {
        assert_eq!(CountingProjection::NAME, "CountingProjection");
    }

    #[test]
    fn test_projection_handled_event_types() {
        let types = CountingProjection::handled_event_types().unwrap();
        assert_eq!(types, vec!["UserCreated", "UserUpdated"]);
    }

    #[test]
    fn test_projection_event_filter_from_handled_types() {
        let filter = CountingProjection::event_filter();

        let matching = create_test_envelope("UserCreated", "User");
        let non_matching = create_test_envelope("OrderCreated", "Order");

        assert!(filter.matches(&matching));
        assert!(!filter.matches(&non_matching));
    }

    #[tokio::test]
    async fn test_projection_handle() {
        let mut proj = CountingProjection { count: 0 };

        let envelope = create_test_envelope("UserCreated", "User");
        proj.handle(&envelope).await.unwrap();

        assert_eq!(*proj.state(), 1);
    }

    #[test]
    fn test_projection_state_mut() {
        let mut proj = CountingProjection { count: 0 };
        *proj.state_mut() = 42;
        assert_eq!(*proj.state(), 42);
    }

    struct AllEventsProjection {
        count: u64,
    }

    #[async_trait]
    impl Projection for AllEventsProjection {
        type State = u64;
        const NAME: &'static str = "AllEventsProjection";

        fn handled_event_types() -> Option<Vec<&'static str>> {
            None
        }

        async fn handle(&mut self, _envelope: &EventEnvelope) -> crate::Result<()> {
            self.count += 1;
            Ok(())
        }

        fn state(&self) -> &u64 {
            &self.count
        }

        fn state_mut(&mut self) -> &mut u64 {
            &mut self.count
        }
    }

    #[test]
    fn test_projection_none_handled_types_gives_all_filter() {
        let filter = AllEventsProjection::event_filter();
        assert_eq!(filter, EventFilter::All);
    }
}
