//! Integration tests for #[aggregate(...)] attribute macro.
//!
//! These tests verify that the aggregate attribute macro correctly generates
//! the Entity and Aggregate trait implementations.

use chrono::{DateTime, Utc};
use event_sauce_core::{
    Aggregate, AggregateError, AggregateRoot, AggregateType, AggregateVersion, ApplyEvent,
    DomainEvent, Entity, EntityId, EventApplicator,
};
use serde::{Deserialize, Serialize};
use thiserror::Error;

// Define error type for testing
#[derive(Debug, Error)]
#[error("Test counter error")]
struct TestCounterError;

impl AggregateError for TestCounterError {}

// Define a simple event for testing
#[derive(Debug, Clone, Serialize, Deserialize)]
enum TestCounterEvent {
    Incremented {
        amount: i32,
        timestamp: DateTime<Utc>,
    },
    Decremented {
        amount: i32,
        timestamp: DateTime<Utc>,
    },
}

impl DomainEvent for TestCounterEvent {
    type Aggregate = TestCounter;

    fn event_type(&self) -> &'static str {
        match self {
            TestCounterEvent::Incremented { .. } => "CounterIncremented",
            TestCounterEvent::Decremented { .. } => "CounterDecremented",
        }
    }

    fn event_version(&self) -> event_sauce_core::EventVersion {
        event_sauce_core::EventVersion::new(1)
    }

    fn occurred_at(&self) -> DateTime<Utc> {
        match self {
            TestCounterEvent::Incremented { timestamp, .. } => *timestamp,
            TestCounterEvent::Decremented { timestamp, .. } => *timestamp,
        }
    }
}

// EventApplicator dispatches to &mut TestCounter (entity) directly
impl EventApplicator<TestCounter> for TestCounterEvent {
    fn dispatch(&self, entity: &mut TestCounter) -> Result<(), TestCounterError> {
        match self {
            TestCounterEvent::Incremented { amount, .. } => {
                entity.value += amount;
            }
            TestCounterEvent::Decremented { amount, .. } => {
                entity.value -= amount;
            }
        }
        Ok(())
    }

    fn dispatch_unchecked(&self, entity: &mut TestCounter) {
        match self {
            TestCounterEvent::Incremented { amount, .. } => {
                entity.value += amount;
            }
            TestCounterEvent::Decremented { amount, .. } => {
                entity.value -= amount;
            }
        }
    }
}

// This is the aggregate struct using the new attribute macro
// The macro generates Entity + Aggregate impls (no wrapper or state struct)
#[event_sauce_macros::aggregate(event = "TestCounterEvent", error = "TestCounterError")]
#[derive(Serialize, Deserialize, Debug, Clone)]
struct TestCounter {
    #[id]
    id: EntityId,
    value: i32,
}
// DefaultEntity is now auto-generated by #[aggregate] macro

#[test]
fn test_aggregate_derive_generates_entity_trait() {
    let id = EntityId::new();
    let counter = TestCounter::new(id);

    // The Entity trait should be implemented
    assert_eq!(counter.entity_id(), id);
    assert_eq!(counter.value, 0);
}

#[test]
fn test_aggregate_derive_entity_id() {
    let id = EntityId::new();
    let counter = TestCounter::new(id);

    assert_eq!(counter.entity_id(), id);
}

#[test]
fn test_aggregate_root_new() {
    let id = EntityId::new();
    let root = AggregateRoot::<TestCounter>::new(id);

    assert_eq!(root.entity_id(), id);
    assert_eq!(root.version(), AggregateVersion::initial());
    assert_eq!(root.pending_events().len(), 0);
}

#[test]
fn test_aggregate_root_apply() {
    let id = EntityId::new();
    let mut root = AggregateRoot::<TestCounter>::new(id);

    let event = TestCounterEvent::Incremented {
        amount: 10,
        timestamp: Utc::now(),
    };

    root.apply(event).unwrap();

    // Version should be incremented
    assert_eq!(root.version(), AggregateVersion::new(1));
    // Value should be updated - accessible via Deref
    assert_eq!(root.value, 10);
    // Pending events recorded
    assert_eq!(root.pending_events().len(), 1);
}

#[test]
fn test_aggregate_root_multiple_events() {
    let id = EntityId::new();
    let mut root = AggregateRoot::<TestCounter>::new(id);

    root.apply(TestCounterEvent::Incremented {
        amount: 5,
        timestamp: Utc::now(),
    })
    .unwrap();
    root.apply(TestCounterEvent::Incremented {
        amount: 3,
        timestamp: Utc::now(),
    })
    .unwrap();

    assert_eq!(root.pending_events().len(), 2);
    assert_eq!(root.value, 8);
    assert_eq!(root.version(), AggregateVersion::new(2));
}

#[test]
fn test_aggregate_root_clear_pending_events() {
    let id = EntityId::new();
    let mut root = AggregateRoot::<TestCounter>::new(id);

    root.apply(TestCounterEvent::Incremented {
        amount: 5,
        timestamp: Utc::now(),
    })
    .unwrap();
    assert_eq!(root.pending_events().len(), 1);

    root.clear_pending_events();
    assert_eq!(root.pending_events().len(), 0);
}

#[test]
fn test_aggregate_derive_is_send_sync() {
    fn assert_send<T: Send>() {}
    fn assert_sync<T: Sync>() {}

    assert_send::<TestCounter>();
    assert_sync::<TestCounter>();
}

#[test]
fn test_aggregate_derive_aggregate_type() {
    let type_name = TestCounter::aggregate_type();
    assert_eq!(type_name, "TestCounter");
}

#[test]
fn test_aggregate_derive_returns_aggregate_type_newtype() {
    let type_name = TestCounter::aggregate_type();
    // Should be an AggregateType, not a bare string
    assert_eq!(type_name, AggregateType::new("TestCounter"));
}

#[test]
fn test_no_state_struct_generated() {
    // In the new design, no separate State struct is generated.
    // The entity struct IS the domain type with direct field access.
    let counter = TestCounter::new(EntityId::new());
    assert_eq!(counter.value, 0);
}

#[test]
fn test_restore() {
    let id = EntityId::new();
    let entity = TestCounter { id, value: 100 };

    let root = AggregateRoot::<TestCounter>::restore(AggregateVersion::new(5), entity);

    assert_eq!(root.value, 100);
    assert_eq!(root.version(), AggregateVersion::new(5));
    assert_eq!(root.entity_id(), id);
}

#[test]
fn test_deref_read_access() {
    let id = EntityId::new();
    let mut root = AggregateRoot::<TestCounter>::new(id);

    root.apply(TestCounterEvent::Incremented {
        amount: 999,
        timestamp: Utc::now(),
    })
    .unwrap();

    // Can read state fields directly via Deref
    assert_eq!(root.value, 999);
}

#[test]
fn test_entity_ref_access() {
    let id = EntityId::new();
    let mut root = AggregateRoot::<TestCounter>::new(id);

    root.apply(TestCounterEvent::Incremented {
        amount: 5,
        timestamp: Utc::now(),
    })
    .unwrap();

    // Can get a reference to the entity
    let entity_ref = root.entity();
    assert_eq!(entity_ref.value, 5);
}

// ============================================================================
// Tests for #[aggregate(type_name = "...")] — custom type name override
// ============================================================================

// Separate event type for the renamed counter (DomainEvent::Aggregate must match)
#[derive(Debug, Clone, Serialize, Deserialize)]
enum RenamedCounterEvent {
    Incremented {
        amount: i32,
        timestamp: DateTime<Utc>,
    },
}

impl DomainEvent for RenamedCounterEvent {
    type Aggregate = RenamedCounter;
    fn event_type(&self) -> &'static str {
        match self {
            RenamedCounterEvent::Incremented { .. } => "RenamedCounter.Incremented",
        }
    }
    fn event_version(&self) -> event_sauce_core::EventVersion {
        event_sauce_core::EventVersion::new(1)
    }
    fn occurred_at(&self) -> DateTime<Utc> {
        match self {
            RenamedCounterEvent::Incremented { timestamp, .. } => *timestamp,
        }
    }
}

impl EventApplicator<RenamedCounter> for RenamedCounterEvent {
    fn dispatch(&self, entity: &mut RenamedCounter) -> Result<(), RenamedCounterError> {
        match self {
            RenamedCounterEvent::Incremented { amount, .. } => entity.value += amount,
        }
        Ok(())
    }

    fn dispatch_unchecked(&self, entity: &mut RenamedCounter) {
        match self {
            RenamedCounterEvent::Incremented { amount, .. } => entity.value += amount,
        }
    }
}

#[derive(Debug, Error)]
#[error("Renamed counter error")]
struct RenamedCounterError;

impl AggregateError for RenamedCounterError {}

#[event_sauce_macros::aggregate(
    event = "RenamedCounterEvent",
    error = "RenamedCounterError",
    type_name = "MyCustomCounter"
)]
#[derive(Serialize, Deserialize, Debug, Clone)]
struct RenamedCounter {
    #[id]
    id: EntityId,
    value: i32,
}

#[test]
fn test_aggregate_custom_type_name_override() {
    let type_name = RenamedCounter::aggregate_type();
    assert_eq!(type_name, "MyCustomCounter");
    assert_eq!(type_name, AggregateType::new("MyCustomCounter"));
}

#[test]
fn test_aggregate_custom_type_name_not_struct_name() {
    let type_name = RenamedCounter::aggregate_type();
    // Should NOT be the struct name
    assert_ne!(type_name, "RenamedCounter");
}

// ============================================================================
// Tests for #[aggregate(init)] — init-event aggregates
// ============================================================================

// An init-event aggregate uses the `init` flag to skip DefaultEntity generation.
// It must be constructed via init events, not Entity::new().

#[derive(Debug, Error)]
#[error("Init aggregate error")]
struct InitAggError;

impl AggregateError for InitAggError {}

#[derive(Debug, Clone, Serialize, Deserialize)]
enum InitAggEvent {
    Created {
        name: String,
        timestamp: chrono::DateTime<Utc>,
    },
}

impl DomainEvent for InitAggEvent {
    type Aggregate = InitAgg;
    fn event_type(&self) -> &'static str {
        match self {
            InitAggEvent::Created { .. } => "InitAgg.Created",
        }
    }
    fn event_version(&self) -> event_sauce_core::EventVersion {
        event_sauce_core::EventVersion::new(1)
    }
    fn occurred_at(&self) -> chrono::DateTime<Utc> {
        match self {
            InitAggEvent::Created { timestamp, .. } => *timestamp,
        }
    }
}

impl event_sauce_core::InitEvent<InitAgg> for InitAggEvent {
    fn init(&self, id: EntityId) -> InitAgg {
        match self {
            InitAggEvent::Created { name, .. } => InitAgg {
                id,
                name: name.clone(),
            },
        }
    }
}

impl EventApplicator<InitAgg> for InitAggEvent {
    fn is_init(&self) -> bool {
        true
    }

    fn dispatch_init(&self, id: EntityId) -> Result<InitAgg, InitAggError> {
        use event_sauce_core::InitEvent;
        self.validate_init()?;
        let entity = self.init(id);
        self.post_validate_init(&entity)?;
        Ok(entity)
    }

    fn dispatch_init_unchecked(&self, id: EntityId) -> InitAgg {
        use event_sauce_core::InitEvent;
        self.init(id)
    }

    fn dispatch(&self, _entity: &mut InitAgg) -> Result<(), InitAggError> {
        unreachable!("init events should not be dispatched as regular events")
    }

    fn dispatch_unchecked(&self, _entity: &mut InitAgg) {
        unreachable!("init events should not be dispatched as regular events")
    }
}

#[event_sauce_macros::aggregate(event = "InitAggEvent", error = "InitAggError", init)]
#[derive(Serialize, Deserialize, Debug, Clone)]
struct InitAgg {
    #[id]
    id: EntityId,
    name: String,
}

#[test]
fn test_aggregate_init_entity_id() {
    // Init aggregates still implement Entity with entity_id()
    let agg = InitAgg {
        id: EntityId::new(),
        name: "test".to_string(),
    };
    let _ = agg.entity_id();
}

#[test]
fn test_aggregate_init_aggregate_trait() {
    // Aggregate trait is still generated
    assert_eq!(InitAgg::aggregate_type(), "InitAgg");
}

#[test]
fn test_aggregate_init_uninit_lifecycle() {
    use event_sauce_core::UninitAggregateRoot;

    let uninit = UninitAggregateRoot::<InitAgg>::new(EntityId::new());
    let id = uninit.entity_id();

    let agg = uninit
        .apply_init(InitAggEvent::Created {
            name: "Alice".to_string(),
            timestamp: Utc::now(),
        })
        .unwrap();

    assert_eq!(agg.entity_id(), id);
    assert_eq!(agg.name, "Alice");
}

// ============================================================================
// Tests for #[aggregate(encrypted)] — encrypted aggregates
// ============================================================================

#[derive(Debug, Error)]
#[error("Private agg error")]
struct PrivateAggError;

impl AggregateError for PrivateAggError {}

#[derive(Debug, Clone, Serialize, Deserialize)]
enum PrivateAggEvent {
    Created { name: String },
}

impl DomainEvent for PrivateAggEvent {
    type Aggregate = PrivateAgg;
    fn event_type(&self) -> &'static str {
        match self {
            PrivateAggEvent::Created { .. } => "PrivateAgg.Created",
        }
    }
    fn event_version(&self) -> event_sauce_core::EventVersion {
        event_sauce_core::EventVersion::new(1)
    }
    fn occurred_at(&self) -> chrono::DateTime<Utc> {
        Utc::now()
    }
}

impl ApplyEvent<PrivateAgg> for PrivateAggEvent {
    fn apply(&self, entity: &mut PrivateAgg) {
        match self {
            PrivateAggEvent::Created { name } => entity.name = name.clone(),
        }
    }
}

impl EventApplicator<PrivateAgg> for PrivateAggEvent {
    fn dispatch(&self, entity: &mut PrivateAgg) -> Result<(), PrivateAggError> {
        ApplyEvent::apply(self, entity);
        Ok(())
    }
    fn dispatch_unchecked(&self, entity: &mut PrivateAgg) {
        ApplyEvent::apply(self, entity);
    }
}

#[event_sauce_macros::aggregate(event = "PrivateAggEvent", error = "PrivateAggError", encrypted)]
#[derive(Serialize, Deserialize, Debug, Clone)]
struct PrivateAgg {
    #[id]
    id: EntityId,
    name: String,
}

#[test]
fn test_aggregate_encrypted_is_encrypted_returns_true() {
    assert!(PrivateAgg::is_encrypted());
}

#[test]
fn test_aggregate_without_encrypted_is_not_encrypted() {
    // TestCounter was defined without `encrypted` — should return false
    assert!(!TestCounter::is_encrypted());
}

#[test]
fn test_aggregate_encrypted_still_generates_entity_trait() {
    let id = EntityId::new();
    let agg = PrivateAgg::new(id);
    assert_eq!(agg.entity_id(), id);
    assert_eq!(agg.name, String::new());
}

#[test]
fn test_aggregate_encrypted_still_generates_aggregate_type() {
    assert_eq!(PrivateAgg::aggregate_type(), "PrivateAgg");
}

#[test]
fn test_aggregate_encrypted_works_with_aggregate_root() {
    let id = EntityId::new();
    let mut root = AggregateRoot::<PrivateAgg>::new(id);

    root.apply(PrivateAggEvent::Created {
        name: "Secret".into(),
    })
    .unwrap();

    assert_eq!(root.name, "Secret");
    assert_eq!(root.version(), AggregateVersion::new(1));
}

// ============================================================================
// Tests for #[aggregate(snapshot_version = N)] — snapshot schema versioning
// ============================================================================

#[derive(Debug, Error)]
#[error("Versioned agg error")]
struct VersionedAggError;

impl AggregateError for VersionedAggError {}

#[derive(Debug, Clone, Serialize, Deserialize)]
enum VersionedAggEvent {
    Created { value: i32 },
}

impl DomainEvent for VersionedAggEvent {
    type Aggregate = VersionedAgg;
    fn event_type(&self) -> &'static str {
        match self {
            VersionedAggEvent::Created { .. } => "VersionedAgg.Created",
        }
    }
    fn event_version(&self) -> event_sauce_core::EventVersion {
        event_sauce_core::EventVersion::new(1)
    }
    fn occurred_at(&self) -> chrono::DateTime<Utc> {
        Utc::now()
    }
}

impl ApplyEvent<VersionedAgg> for VersionedAggEvent {
    fn apply(&self, entity: &mut VersionedAgg) {
        match self {
            VersionedAggEvent::Created { value } => entity.value = *value,
        }
    }
}

impl EventApplicator<VersionedAgg> for VersionedAggEvent {
    fn dispatch(&self, entity: &mut VersionedAgg) -> Result<(), VersionedAggError> {
        ApplyEvent::apply(self, entity);
        Ok(())
    }
    fn dispatch_unchecked(&self, entity: &mut VersionedAgg) {
        ApplyEvent::apply(self, entity);
    }
}

#[event_sauce_macros::aggregate(
    event = "VersionedAggEvent",
    error = "VersionedAggError",
    snapshot_version = 3
)]
#[derive(Serialize, Deserialize, Debug, Clone)]
struct VersionedAgg {
    #[id]
    id: EntityId,
    value: i32,
}

#[test]
fn test_aggregate_snapshot_version_override() {
    assert_eq!(VersionedAgg::snapshot_version(), 3);
}

#[test]
fn test_aggregate_default_snapshot_version_is_zero() {
    // TestCounter was defined without `snapshot_version` — should default to 0.
    assert_eq!(TestCounter::snapshot_version(), 0);
}

// ============================================================================
// Tests for typed AggregateId in #[aggregate] struct
// ============================================================================

// Typed ID newtype — wraps EntityId with compile-time aggregate association
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, event_sauce_macros::AggregateId,
)]
#[aggregate_id(TypedIdAgg)]
struct TypedIdAggId(EntityId);

#[derive(Debug, thiserror::Error)]
#[error("typed id aggregate error")]
struct TypedIdAggError;

impl AggregateError for TypedIdAggError {}

#[derive(Debug, Clone, Serialize, Deserialize)]
enum TypedIdAggEvent {
    Created {
        name: String,
        timestamp: chrono::DateTime<chrono::Utc>,
    },
}

impl DomainEvent for TypedIdAggEvent {
    type Aggregate = TypedIdAgg;
    fn event_type(&self) -> &'static str {
        match self {
            TypedIdAggEvent::Created { .. } => "TypedIdAgg.Created",
        }
    }
    fn event_version(&self) -> event_sauce_core::EventVersion {
        event_sauce_core::EventVersion::new(1)
    }
    fn occurred_at(&self) -> chrono::DateTime<chrono::Utc> {
        match self {
            TypedIdAggEvent::Created { timestamp, .. } => *timestamp,
        }
    }
}

impl ApplyEvent<TypedIdAgg> for TypedIdAggEvent {
    fn apply(&self, entity: &mut TypedIdAgg) {
        match self {
            TypedIdAggEvent::Created { name, .. } => {
                entity.name = name.clone();
            }
        }
    }
}

impl EventApplicator<TypedIdAgg> for TypedIdAggEvent {
    fn dispatch(&self, entity: &mut TypedIdAgg) -> Result<(), TypedIdAggError> {
        self.apply(entity);
        Ok(())
    }
    fn dispatch_unchecked(&self, entity: &mut TypedIdAgg) {
        self.apply(entity);
    }
}

/// Aggregate with a typed ID field — uses TypedIdAggId instead of EntityId.
#[event_sauce_macros::aggregate(event = "TypedIdAggEvent", error = "TypedIdAggError")]
#[derive(Debug, Clone, Serialize, Deserialize)]
struct TypedIdAgg {
    #[id]
    id: TypedIdAggId,
    name: String,
}

#[test]
fn test_typed_id_aggregate_entity_id() {
    let raw_id = EntityId::new();
    let agg = TypedIdAgg {
        id: TypedIdAggId(raw_id),
        name: "test".to_string(),
    };
    // entity_id() still returns EntityId
    assert_eq!(agg.entity_id(), raw_id);
}

#[test]
fn test_typed_id_aggregate_id_method() {
    let raw_id = EntityId::new();
    let agg = TypedIdAgg {
        id: TypedIdAggId(raw_id),
        name: "test".to_string(),
    };
    // id() returns the typed ID
    let typed_id: TypedIdAggId = agg.id();
    assert_eq!(*typed_id, raw_id);
}

#[test]
fn test_typed_id_aggregate_new_converts_entity_id() {
    use event_sauce_core::Entity;
    let raw_id = EntityId::new();
    // Entity::new() takes EntityId and converts to TypedIdAggId internally
    let agg = TypedIdAgg::new(raw_id);
    assert_eq!(agg.entity_id(), raw_id);
    assert_eq!(*agg.id(), raw_id);
}

#[test]
fn test_typed_id_aggregate_root_id_via_deref() {
    let raw_id = EntityId::new();
    let mut root = AggregateRoot::<TypedIdAgg>::new(raw_id);

    root.apply(TypedIdAggEvent::Created {
        name: "Alice".into(),
        timestamp: chrono::Utc::now(),
    })
    .unwrap();

    // entity_id() returns EntityId (from AggregateRoot directly)
    assert_eq!(root.entity_id(), raw_id);
    // id() returns TypedIdAggId (from TypedIdAgg::id() via Deref)
    let typed_id: TypedIdAggId = root.id();
    assert_eq!(*typed_id, raw_id);
    assert_eq!(root.name, "Alice");
}
