//! Tests for the `user_message_key()` method generated by `#[derive(AggregateError)]`.
//!
//! The derive maps each enum variant to a stable `&'static str` fluent key of
//! the shape `{prefix}-error-{variant-kebab}`, where `prefix` is the enum name
//! with a trailing `Error` stripped and kebab-cased. A `#[message_key("…")]`
//! attribute overrides the key for an individual variant.

use event_sauce_macros::AggregateError;
use thiserror::Error;

#[derive(AggregateError, Debug, Error)]
enum WidgetError {
    #[error("empty")]
    EmptyTitle,
    #[error("co-org")]
    CoOrganiserNotFound,
    #[error("rsvp")]
    RsvpDeadlinePassed,
    #[error("status {0}")]
    InvalidStatusForAction(u8),
    #[error("named")]
    WithNamedFields { id: u32 },
    #[error("override")]
    #[message_key("widget-error-custom-override")]
    SomethingRenamed,
}

#[test]
fn unit_variant_uses_kebab_key() {
    assert_eq!(
        WidgetError::EmptyTitle.user_message_key(),
        "widget-error-empty-title"
    );
}

#[test]
fn multiword_and_acronym_variants_kebab_correctly() {
    assert_eq!(
        WidgetError::CoOrganiserNotFound.user_message_key(),
        "widget-error-co-organiser-not-found"
    );
    assert_eq!(
        WidgetError::RsvpDeadlinePassed.user_message_key(),
        "widget-error-rsvp-deadline-passed"
    );
}

#[test]
fn tuple_variant_ignores_payload() {
    assert_eq!(
        WidgetError::InvalidStatusForAction(3).user_message_key(),
        "widget-error-invalid-status-for-action"
    );
}

#[test]
fn struct_variant_ignores_fields() {
    assert_eq!(
        WidgetError::WithNamedFields { id: 1 }.user_message_key(),
        "widget-error-with-named-fields"
    );
}

#[test]
fn message_key_attribute_overrides_default() {
    assert_eq!(
        WidgetError::SomethingRenamed.user_message_key(),
        "widget-error-custom-override"
    );
}
